[package]
name = "dualis-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
reqwest = {version="^0.11", features = ["cookies"]}
select = "0.6.0"
serde = "^1.0.152"
